version: '3'
services:
  moi-database:
    image: "mysql:5.7"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
    ports:
      - "${DB_PORT:-33061}:3306"
  web:
    env_file:
      - variables.env
    build: .
    image: "lucerodocker/moi"
    ports:
      - "${WEB_PORT:-9091}:9091"
    depends_on:
      - moi-database
    restart: on-failure
